version: '3.8'

services:
  pyattender:
    build: .
    container_name: pyattender
    ports:
      - "8188:8188"
    volumes:
      - ./Raw:/app/Raw
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - TZ=America/New_York  # Set timezone to match application's ET timezone(base)